-- 创建用户
CREATE USER docadmin WITH PASSWORD 'zs1o2PAoPBNF7yi0oxo2';

-- 创建数据库（如果需要）
CREATE DATABASE db_document OWNER docadmin;

-- 授权数据库级别权限
GRANT ALL PRIVILEGES ON DATABASE db_document TO docadmin;

-- 授权 schema 中所有对象
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO docadmin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO docadmin;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO docadmin;

-- 设置默认权限
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO docadmin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO docadmin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO docadmin;